"""Type stub for the C++ extension optisocks5._core (the sans-IO SOCKS5 codec).

Signatures mirror the PyMethodDef table in csrc/module.cpp. Parsers return None
on a malformed/truncated frame; builders raise ValueError on out-of-range ints
or oversize length-prefixed fields.
"""

# ---- TCP control channel: client side --------------------------------------
def client_greeting(methods: bytes) -> bytes: ...
def parse_method_selection(data: bytes) -> int | None: ...
def userpass_auth(user: str, password: str) -> bytes: ...
def parse_auth_reply(data: bytes) -> int | None: ...
def request(cmd: int, host: str, port: int) -> bytes: ...
def parse_reply(data: bytes) -> tuple[int, str, int] | None: ...

# ---- TCP control channel: server side --------------------------------------
def parse_greeting(data: bytes) -> bytes | None: ...
def method_selection(method: int) -> bytes: ...
def parse_userpass(data: bytes) -> tuple[str, str] | None: ...
def auth_reply(status: int) -> bytes: ...
def parse_request(data: bytes) -> tuple[int, str, int] | None: ...
def reply(rep: int, host: str, port: int) -> bytes: ...

# ---- UDP data channel ------------------------------------------------------
def udp_encapsulate(host: str, port: int, payload: bytes, frag: int = 0) -> bytes: ...
def udp_decapsulate(data: bytes) -> tuple[int, str, int, bytes] | None: ...
